// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ordermanage.proxies;

public class Order
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OrderManage.Order";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		orderNo("orderNo"),
		partNo("partNo"),
		product("product"),
		groupName("groupName"),
		setupStart("setupStart"),
		startTime("startTime"),
		endTime("endTime"),
		quantity("quantity"),
		actualQuantity("actualQuantity"),
		acSetupTime("acSetupTime"),
		acStartTime("acStartTime"),
		acEndTime("acEndTime"),
		note("note"),
		orderStatus("orderStatus");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Order(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Order(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject)
	{
		if (orderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, orderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderMendixObject = orderMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Order.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ordermanage.proxies.Order initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ordermanage.proxies.Order.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static ordermanage.proxies.Order initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ordermanage.proxies.Order(context, mendixObject);
	}

	public static ordermanage.proxies.Order load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ordermanage.proxies.Order.initialize(context, mendixObject);
	}

	public static java.util.List<ordermanage.proxies.Order> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> ordermanage.proxies.Order.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of orderNo
	 */
	public final java.lang.Integer getorderNo()
	{
		return getorderNo(getContext());
	}

	/**
	 * @param context
	 * @return value of orderNo
	 */
	public final java.lang.Integer getorderNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.orderNo.toString());
	}

	/**
	 * Set value of orderNo
	 * @param orderno
	 */
	public final void setorderNo(java.lang.Integer orderno)
	{
		setorderNo(getContext(), orderno);
	}

	/**
	 * Set value of orderNo
	 * @param context
	 * @param orderno
	 */
	public final void setorderNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer orderno)
	{
		getMendixObject().setValue(context, MemberNames.orderNo.toString(), orderno);
	}

	/**
	 * @return value of partNo
	 */
	public final java.lang.String getpartNo()
	{
		return getpartNo(getContext());
	}

	/**
	 * @param context
	 * @return value of partNo
	 */
	public final java.lang.String getpartNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.partNo.toString());
	}

	/**
	 * Set value of partNo
	 * @param partno
	 */
	public final void setpartNo(java.lang.String partno)
	{
		setpartNo(getContext(), partno);
	}

	/**
	 * Set value of partNo
	 * @param context
	 * @param partno
	 */
	public final void setpartNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partno)
	{
		getMendixObject().setValue(context, MemberNames.partNo.toString(), partno);
	}

	/**
	 * @return value of product
	 */
	public final java.lang.String getproduct()
	{
		return getproduct(getContext());
	}

	/**
	 * @param context
	 * @return value of product
	 */
	public final java.lang.String getproduct(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.product.toString());
	}

	/**
	 * Set value of product
	 * @param product
	 */
	public final void setproduct(java.lang.String product)
	{
		setproduct(getContext(), product);
	}

	/**
	 * Set value of product
	 * @param context
	 * @param product
	 */
	public final void setproduct(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String product)
	{
		getMendixObject().setValue(context, MemberNames.product.toString(), product);
	}

	/**
	 * @return value of groupName
	 */
	public final java.lang.String getgroupName()
	{
		return getgroupName(getContext());
	}

	/**
	 * @param context
	 * @return value of groupName
	 */
	public final java.lang.String getgroupName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.groupName.toString());
	}

	/**
	 * Set value of groupName
	 * @param groupname
	 */
	public final void setgroupName(java.lang.String groupname)
	{
		setgroupName(getContext(), groupname);
	}

	/**
	 * Set value of groupName
	 * @param context
	 * @param groupname
	 */
	public final void setgroupName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String groupname)
	{
		getMendixObject().setValue(context, MemberNames.groupName.toString(), groupname);
	}

	/**
	 * @return value of setupStart
	 */
	public final java.util.Date getsetupStart()
	{
		return getsetupStart(getContext());
	}

	/**
	 * @param context
	 * @return value of setupStart
	 */
	public final java.util.Date getsetupStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.setupStart.toString());
	}

	/**
	 * Set value of setupStart
	 * @param setupstart
	 */
	public final void setsetupStart(java.util.Date setupstart)
	{
		setsetupStart(getContext(), setupstart);
	}

	/**
	 * Set value of setupStart
	 * @param context
	 * @param setupstart
	 */
	public final void setsetupStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date setupstart)
	{
		getMendixObject().setValue(context, MemberNames.setupStart.toString(), setupstart);
	}

	/**
	 * @return value of startTime
	 */
	public final java.util.Date getstartTime()
	{
		return getstartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of startTime
	 */
	public final java.util.Date getstartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.startTime.toString());
	}

	/**
	 * Set value of startTime
	 * @param starttime
	 */
	public final void setstartTime(java.util.Date starttime)
	{
		setstartTime(getContext(), starttime);
	}

	/**
	 * Set value of startTime
	 * @param context
	 * @param starttime
	 */
	public final void setstartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.startTime.toString(), starttime);
	}

	/**
	 * @return value of endTime
	 */
	public final java.util.Date getendTime()
	{
		return getendTime(getContext());
	}

	/**
	 * @param context
	 * @return value of endTime
	 */
	public final java.util.Date getendTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.endTime.toString());
	}

	/**
	 * Set value of endTime
	 * @param endtime
	 */
	public final void setendTime(java.util.Date endtime)
	{
		setendTime(getContext(), endtime);
	}

	/**
	 * Set value of endTime
	 * @param context
	 * @param endtime
	 */
	public final void setendTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.endTime.toString(), endtime);
	}

	/**
	 * @return value of quantity
	 */
	public final java.lang.Integer getquantity()
	{
		return getquantity(getContext());
	}

	/**
	 * @param context
	 * @return value of quantity
	 */
	public final java.lang.Integer getquantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.quantity.toString());
	}

	/**
	 * Set value of quantity
	 * @param quantity
	 */
	public final void setquantity(java.lang.Integer quantity)
	{
		setquantity(getContext(), quantity);
	}

	/**
	 * Set value of quantity
	 * @param context
	 * @param quantity
	 */
	public final void setquantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantity)
	{
		getMendixObject().setValue(context, MemberNames.quantity.toString(), quantity);
	}

	/**
	 * @return value of actualQuantity
	 */
	public final java.lang.Integer getactualQuantity()
	{
		return getactualQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of actualQuantity
	 */
	public final java.lang.Integer getactualQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.actualQuantity.toString());
	}

	/**
	 * Set value of actualQuantity
	 * @param actualquantity
	 */
	public final void setactualQuantity(java.lang.Integer actualquantity)
	{
		setactualQuantity(getContext(), actualquantity);
	}

	/**
	 * Set value of actualQuantity
	 * @param context
	 * @param actualquantity
	 */
	public final void setactualQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer actualquantity)
	{
		getMendixObject().setValue(context, MemberNames.actualQuantity.toString(), actualquantity);
	}

	/**
	 * @return value of acSetupTime
	 */
	public final java.util.Date getacSetupTime()
	{
		return getacSetupTime(getContext());
	}

	/**
	 * @param context
	 * @return value of acSetupTime
	 */
	public final java.util.Date getacSetupTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.acSetupTime.toString());
	}

	/**
	 * Set value of acSetupTime
	 * @param acsetuptime
	 */
	public final void setacSetupTime(java.util.Date acsetuptime)
	{
		setacSetupTime(getContext(), acsetuptime);
	}

	/**
	 * Set value of acSetupTime
	 * @param context
	 * @param acsetuptime
	 */
	public final void setacSetupTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date acsetuptime)
	{
		getMendixObject().setValue(context, MemberNames.acSetupTime.toString(), acsetuptime);
	}

	/**
	 * @return value of acStartTime
	 */
	public final java.util.Date getacStartTime()
	{
		return getacStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of acStartTime
	 */
	public final java.util.Date getacStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.acStartTime.toString());
	}

	/**
	 * Set value of acStartTime
	 * @param acstarttime
	 */
	public final void setacStartTime(java.util.Date acstarttime)
	{
		setacStartTime(getContext(), acstarttime);
	}

	/**
	 * Set value of acStartTime
	 * @param context
	 * @param acstarttime
	 */
	public final void setacStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date acstarttime)
	{
		getMendixObject().setValue(context, MemberNames.acStartTime.toString(), acstarttime);
	}

	/**
	 * @return value of acEndTime
	 */
	public final java.util.Date getacEndTime()
	{
		return getacEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of acEndTime
	 */
	public final java.util.Date getacEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.acEndTime.toString());
	}

	/**
	 * Set value of acEndTime
	 * @param acendtime
	 */
	public final void setacEndTime(java.util.Date acendtime)
	{
		setacEndTime(getContext(), acendtime);
	}

	/**
	 * Set value of acEndTime
	 * @param context
	 * @param acendtime
	 */
	public final void setacEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date acendtime)
	{
		getMendixObject().setValue(context, MemberNames.acEndTime.toString(), acendtime);
	}

	/**
	 * @return value of note
	 */
	public final java.lang.String getnote()
	{
		return getnote(getContext());
	}

	/**
	 * @param context
	 * @return value of note
	 */
	public final java.lang.String getnote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.note.toString());
	}

	/**
	 * Set value of note
	 * @param note
	 */
	public final void setnote(java.lang.String note)
	{
		setnote(getContext(), note);
	}

	/**
	 * Set value of note
	 * @param context
	 * @param note
	 */
	public final void setnote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String note)
	{
		getMendixObject().setValue(context, MemberNames.note.toString(), note);
	}

	/**
	 * Set value of orderStatus
	 * @param orderstatus
	 */
	public final ordermanage.proxies.Status_Title getorderStatus()
	{
		return getorderStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of orderStatus
	 */
	public final ordermanage.proxies.Status_Title getorderStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.orderStatus.toString());
		if (obj == null) {
			return null;
		}
		return ordermanage.proxies.Status_Title.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of orderStatus
	 * @param orderstatus
	 */
	public final void setorderStatus(ordermanage.proxies.Status_Title orderstatus)
	{
		setorderStatus(getContext(), orderstatus);
	}

	/**
	 * Set value of orderStatus
	 * @param context
	 * @param orderstatus
	 */
	public final void setorderStatus(com.mendix.systemwideinterfaces.core.IContext context, ordermanage.proxies.Status_Title orderstatus)
	{
		if (orderstatus != null) {
			getMendixObject().setValue(context, MemberNames.orderStatus.toString(), orderstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.orderStatus.toString(), null);
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ordermanage.proxies.Order that = (ordermanage.proxies.Order) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
