// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ordermanage.proxies;

public enum Status_Title
{
	Create(new java.lang.String[][] { new java.lang.String[] { "en_US", "Create" } }),
	Pending(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pending" } }),
	Accepted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Accepted" } }),
	Release(new java.lang.String[][] { new java.lang.String[] { "en_US", "Release" } }),
	Start_Setup(new java.lang.String[][] { new java.lang.String[] { "en_US", "Start Setup" } }),
	Start_Time(new java.lang.String[][] { new java.lang.String[] { "en_US", "Start Time" } }),
	Paused(new java.lang.String[][] { new java.lang.String[] { "en_US", "Paused" } }),
	Canceled(new java.lang.String[][] { new java.lang.String[] { "en_US", "Canceled" } }),
	Finished(new java.lang.String[][] { new java.lang.String[] { "en_US", "Finished" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Status_Title(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
